title:              EJ's Blog ğŸ‘©ğŸ»â€ğŸ’»
email:              silverji703@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Start Bootstrap
baseurl:            ""
url:                "silverjii.github.io"

# Social Profiles
github_username:    silverjii

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
